const brownDwarf = {
  id: "brown_dwarf",
  name: "Debris Field",
  description:
    "Human-scale remnants of a shattered rocky planet orbit a dim brown dwarf.",

  spawn: {
    position: [0, 0, -240],
    target: [78, 14, 12],
  },

  player: {
    speed: 2,
    boostSpeed: 4.8,
  },

  platform: {
    id: "interceptor_platform",
    modelUrl: "./assets/teo_ship.glb",
    modelMaxSize: 2.145,
    physicsBounds: {
      min: [-1.0297, -0.3962, -1.0365],
      max: [1.0297, 1.0725, 1.0365],
    },
    modelRotationDegrees: [0, 180, 0],
    widthMeters: 24,
    depthMeters: 24,
    thicknessMeters: 0.35,
    eyeHeightMeters: 8.32,
    playerHeightScale: 0.8,
    lightHeightMeters: 2.6,
    lightRangeMeters: 0,
    lightIntensity: 0,
    allowLocalLights: false,
    transparentGlass: false,
    doorGlass: false,
    doorHingeAxis: "x",
    doorHingeEdge: "minZ",
    doorOpenAngleDegrees: -105,
    doorInteractionProxyScale: 2.9,
    doorInteractionProxyDepth: 0.28,
    brownDwarfWindowShadows: true,
    shadowMapSize: 1024,
    metersPerWorldUnit: 8,
    gravity: 30,
    jumpSpeed: 5.4,
    floorProps: [],
  },

  lighting: {
    starAmbient: 0,
  },

  sky: {
    seed: 2300,
    radius: 900,
    background: ["#02040b", "#000000"],
    starLayers: [
      { count: 3600, pointSize: 1.0, brightness: 0.46 },
      { count: 520, pointSize: 1.5, brightness: 0.68 },
      { count: 70, pointSize: 2.2, brightness: 0.88 },
    ],
  },

  debrisField: {
    id: "shattered_planet_debris_field",
    material: "differentiated rocky-planet fragments",
    fragmentSizeMeters: [2.5, 16.7],
    metersPerWorldUnit: 8,
    composition:
      "Mafic basalt, silicate crust and mantle, feldspar, and nickel-iron fragments.",
    seed: 23017,
    position: [0, 0, 0],
    rotation: [0.08, -0.35, 0.12],
    radius: 620,
    nearFragmentCount: 720,
    maxActiveRocks: 520,
    initialRockGraceRadius: 2.2,
    protectedSpawnRadius: 2.2,
    shipGraceRadius: 2.2,
    guaranteedFrontRock: true,
    guaranteedFrontRockDistance: 4.2,
    guaranteedFrontRockSizeMeters: 6,
    rockRenderDistance: 240,
    rockClumpCount: 7,
    rockClumpRadius: 14,
    rockClumpDistance: 108,
    rockStableDistance: 132,
    rockFadeStart: 172,
    rockFadeEnd: 238,
    rockTransitionSeconds: 3.2,
    coOrbitFraction: 0.8,
    relativeDriftSpeed: 0.045,
    fastRelativeDriftSpeed: 2.6,
    interceptClumpCount: 7,
    interceptClumpDistance: [6, 94],
    nearRockDensityBypassRadius: 32,
    rockDensityGain: 3.2,
    rockDensityThreshold: 0.15,
    rockDensityExponent: 1.6,
    nearRockFlowSpeed: 0,
    minSpinRadiansPerSecond: 0.015,
    maxSpinRadiansPerSecond: 0.09,
    rockMeshSubdivisions: 4,
    rockOpaqueFade: true,
    rockFadeMinScale: 0.12,
    rockDensityUpdateInterval: 6,
    rockLightIntensity: 0,
    rockColorLift: 0.045,
    rockAmbientLift: 0.028,
    rockTextureColorLift: 0.035,
    rockTextureTiling: 3.6,
    rockNormalStrength: 1.65,
    rockParallaxScaleBias: 0.026,
    renderScale: 0.5,
    volumeResolution: 40,
    occupancyResolution: 10,
    marchSteps: 16,
    minimumMarchSteps: 10,
    temporalBlend: 0.86,
    updateInterval: 2,
    adaptiveQuality: true,
    density: 0.46,
    absorption: 0.68,
    emissionStrength: 1.08,
    anisotropy: 0.38,
    // Brown dwarf radius is 70 and this volume radius is 620, so the surface
    // sits at ~0.113 in normalized nebula coordinates. Start slightly inside
    // the occluded body so the same dense cloud visibly reaches the surface.
    innerVoid: 0.07,
    outerSoftness: 0.2,
    // Fresh mafic rind -> gunmetal basalt -> iron-rich crust -> pale fracture.
    // The brown dwarf shifts the directly lit end toward muted amber.
    coolColor: [0.075, 0.095, 0.11],
    violetColor: [0.24, 0.23, 0.215],
    warmColor: [0.58, 0.285, 0.12],
    hotColor: [1.18, 0.66, 0.27],
    coreColor: [2.05, 1.72, 1.18],
    dustColor: [0.004, 0.0035, 0.003],
  },

  brownDwarfImpacts: {
    id: "debris_reentry_impacts",
    seed: 91427,
    spawnRatePerSecond: 34,
    maxImpacts: 820,
    initialImpactCount: 240,
    showEntryTrails: false,
    showImpactCores: true,
    showImpactBlooms: true,
    showAtmosphericScars: true,
    sizeRange: [0.48, 4.95],
    sizePower: 2.6,
    surfaceLift: 0.42,
    entryHeightRange: [12, 42],
    entrySecondsRange: [0.38, 1.08],
    plumeSecondsRange: [1.1, 2.4],
    scarSecondsRange: [5.0, 10.0],
    timeScaleInfluence: 0.45,
  },

  spriteTypes: {
    brownDwarf: {
      shape: "brownDwarf",
      radius: 1,
      color: [150, 72, 45],
      glow: 0.35,
      metadata: {
        massJupiter: 50,
        radiusJupiter: 1,
        estimatedTemperatureK: 950,
        spectralStyle: "cool T-type",
        atmosphere:
          "Dim near-visible glow, methane absorption, and patchy sulfide/silicate cloud bands.",
      },
    },
  },

  sprites: [
    {
      id: "central_brown_dwarf",
      type: "brownDwarf",
      position: [0, 0, 0],
      scale: 70,
      rotation: -0.08,
      lightIntensity: 2.2,
      lightRange: 1600,
      tags: ["star", "brown_dwarf", "navigation_anchor"],
    },
  ],
  structureTypes: {},
  structures: [],
  signals: [],
};

export default brownDwarf;
